apiVersion: v1
kind: ConfigMap
metadata:
  name: apacherr-80-config
  namespace: apacherr
data:
  proxy-home.conf: |
    <VirtualHost *:80>
    ServerAdmin email@example.com
    DocumentRoot /usr/local/apache2/htdocs/
    ServerName www.example.com
    ServerAlias example
    ErrorLog logs/example-error_log
    CustomLog logs/example-access_log combined

    Timeout 300
    KeepAlive On
    MaxKeepAliveRequests 100
    KeepAliveTimeout 15

    ProxyRequests Off
    ProxyPreserveHost On
    UseCanonicalName On
    <Location />
    ProxyPass  http://cms.example.local/
    </Location>
    <Location /customers/>
    ProxyPass  http://customers.secure.local/
    </Location>
    <Location /secure/>
    ProxyPreserveHost off
    ProxyPass  http://secure.example.local/
    </Location>
    </VirtualHost>
  security-headers.conf: |
    Header always set X-XSS-Protection: "1; mode=block"
    Header always set X-Content-Type-Options: "nosniff"
    Header always set X-Frame-Options: "SAMEORIGIN"
    Header always set Content-Security-Policy: "default-src 'self'"
    Header always set Referrer-Policy: "strict-origin-when-cross-origin"
    Header always set Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"

